


CC      =       \nipc\batch.ipc\mc

ASM     =       \nipc\batch.ipc\asm

LINK    =       \nipc\batch.ipc\ml

PCADEP  =       \nipc\pca\npca.h

MODDEP  =       \nipc\common.ipc\mod.h\
                \nipc\common.ipc\os.h

VIDDEP  =       \nipc\video\text\video.h

DESTNAME=       itc.exe

!if $d(DEST)
$(DEST)\$(DESTNAME) : $(DESTNAME)
        copy $(DESTNAME) $(DEST)
!endif

$(DESTNAME): itc.obj ..\multthrd.obj
        $(LINK) itc ..\multthrd

itc.obj : itc.c $(MODDEP) $(VIDDEP) $(PCADEP) ..\multthrd.h
        $(CC) itc

..\multthrd.obj : ..\multthrd.c ..\multthrd.h $(MODDEP) $(PCADEP) $(VIDDEP)
        cd ..
        make -fmakemt
        cd itc
