
CC      =       bcc @\nipc\batch.ipc\resexe.fil

ASM     =       \nipc\batch.ipc\asm

LINK    =       tlink /v/m/s

OBJS    =       hugehead.obj    \
                loader.obj      \
                exec.obj        \
                swapper.obj     \
                miscrou.obj     \
                osdisk.obj      \
                memory.obj


!if $d(OSNAME)
DESTNAME=       $(OSNAME).exe
!else
DESTNAME=       loader.exe
!endif

!if $d(DEST)
$(DEST)\$(DESTNAME) : $(DESTNAME)
        copy $(DESTNAME) $(DEST)
!endif


$(DESTNAME) : $(OBJS)
        $(LINK) hugehead loader exec swapper miscrou osdisk memory, \
                $(DESTNAME),loader,\nipc\common.ipc\jimos
#        del *.obj

loader.obj : loader.c \nipc\common.ipc\os.h
        $(CC) $(CXFLAGS) loader.c

exec.obj : exec.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) exec.asm

swapper.obj : swapper.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) swapper.asm

hugehead.obj : hugehead.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) hugehead.asm

miscrou.obj : miscrou.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) miscrou.asm

osdisk.obj : osdisk.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) osdisk.asm

memory.obj : memory.asm \nipc\common.ipc\os.equ
        $(ASM) $(ASMXFLAGS) memory.asm


