/* Definition of the control structure for streams
*/
typedef struct  {
        int             level;          /* fill/empty level of buffer */
        unsigned        flags;          /* File status flags          */
        char            fd;             /* File descriptor            */
        unsigned char   hold;           /* Ungetc char if no buffer   */
        int             bsize;          /* Buffer size                */
        unsigned char   _FAR *buffer;   /* Data transfer buffer       */
        unsigned char   _FAR *curp;     /* Current active pointer     */
        unsigned        istemp;         /* Temporary file indicator   */
        short           token;          /* Used for validity checking */
}       FILE;                           /* This is the FILE object    */


#define FILENAME_MAX 80

/* Default buffer size use by "setbuf" function
*/
#define BUFSIZ  512         /* Buffer size for stdio */

/* Size of an arry large enough to hold a temporary file name string
*/
#define L_ctermid   5       /* CON: plus null byte */
#define P_tmpdir    ""      /* temporary directory */
#define L_tmpnam    13      /* tmpnam buffer size */

/* Constants to be used as 3rd argument for "fseek" function
*/
#define SEEK_CUR    1
#define SEEK_END    2
#define SEEK_SET    0

/* Number of unique file names that shall be generated by "tmpnam" function
*/
#define TMP_MAX     0xFFFF

/* Standard I/O predefined streams
    streams that need to be created
   stdin
   stdout
   stderr
*/

void     clearerr(FILE far *__stream);
int      fclose(FILE far *__stream);
int      fflush(FILE far *__stream);
int      fgetc(FILE far *__stream);
int      fgetpos(FILE far *__stream, fpos_t far *__pos);
char   far *  fgets(char far *__s, int __n, FILE far *__stream);
FILE   far *  fopen(const char far *__path, const char far *__mode);
int      fprintf(FILE far *__stream, const char far *__format, ...);
int      fputc(int __c, FILE far *__stream);
int      fputs(const char far *__s, FILE far *__stream);
size_t   fread(void far *__ptr, size_t __size, size_t __n,
                     FILE far *__stream);
FILE   far *  freopen(const char far *__path, const char far *__mode,
                            FILE far *__stream);
int      fscanf(FILE far *__stream, const char far *__format, ...);
int      fseek(FILE far *__stream, long __offset, int __whence);
int      fsetpos(FILE far *__stream, const fpos_t far *__pos);
long     ftell(FILE far *__stream);
size_t   fwrite(const void far *__ptr, size_t __size, size_t __n,
                      FILE far *__stream);
char   far * gets(char far *__s);
void     perror(const char far *__s);
int      printf(const char far *__format, ...);
int      puts(const char far *__s);
int      remove(const char far *__path);
int      rename(const char far *__oldname,const char far *__newname);
void     rewind(FILE far *__stream);
int      scanf(const char far *__format, ...);
void     setbuf(FILE far *__stream, char far *__buf);
int       setvbuf(FILE far *__stream, char far *__buf,
                       int __type, size_t __size);
int       sprintf(char far *__buffer, const char far *__format, ...);
int       sscanf(const char far *__buffer,
                      const char far *__format, ...);
char   far *  strerror(int __errnum);
FILE   far *  tmpfile(void);
char   far *  tmpnam(char far *__s);
int       ungetc(int __c, FILE far *__stream);
int       vfprintf(FILE far *__stream, const char far *__format,
                        void far *__arglist);
int       vfscanf(FILE far *__stream, const char far *__format,
                        void far *__arglist);
int      vprintf(const char far *__format, void far *__arglist);
int      vscanf(const char far *__format, void far *__arglist);
int       vsprintf(char far *__buffer, const char far *__format,
                        void far *__arglist);
int       vsscanf(const char far *__buffer, const char far *__format,
                        void far *__arglist);
int      unlink(const char far *__path);
int      getc(FILE far *__fp);

int      getchar(void);
int      putchar(const int __c);

int      putc(const int __c, FILE far *__fp);
int      feof(FILE far *__fp);
int      ferror(FILE far *__fp);


#if !__STDC__
int       fcloseall(void);
FILE   far *  fdopen(int __handle, char far *__type);
int       fgetchar(void);
int       flushall(void);
int       fputchar(int __c);
FILE   far *  _fsopen (const char far *__path, const char far *__mode,
                  int __shflag);
int      getw(FILE far *__stream);
int      putw(int __w, FILE far *__stream);
int      rmtmp(void);
char   far *   _strerror(const char far *__s);
char   far *   tempnam(char far *__dir, char far *__pfx);

#define fileno(f)       ((f)->fd)

#endif  /* !__STDC__ */

int        _fgetc(FILE far *__stream);           /* used by getc() macro */
int        _fputc(char __c, FILE far *__stream); /* used by putc() macro */

/*  The following macros provide for common functions */

#define ferror(f)   ((f)->flags & _F_ERR)
#define feof(f)     ((f)->flags & _F_EOF)

#define getc(f) \
  ((--((f)->level) >= 0) ? (unsigned char)(*(f)->curp++) : \
    _fgetc (f))

#define putc(c,f) \
  ((++((f)->level) < 0) ? (unsigned char)(*(f)->curp++=(c)) : \
    _fputc ((c),f))

#define getchar()  getc(stdin)
#define putchar(c) putc((c), stdout)

#define ungetc(c,f) ungetc((c),f)   /* traditionally a macro */

#endif

enum Indents
{
  WINDOW,
  DISK,
  ETHER,
  COMM,
  KEYBOARD
}

typedef struct stream_type
{
  char identity;
  void far *pointer;
} stream_type;

#define VARIABLE_LIST ...

stream_type stdout={WINDOW,0},
            stdin={WINDOW,0},
            stderr={WINDOW,0};



int wprintf(windowptr output,char far *format,short far *extras)
{
  while (*format)
  {
    if (*format=='%')
    {
      format++;
      switch(*format)
      {
        case '%':
          display(output,*format);
          break;
      }
    }
    else
      display(output,*format);
    format++;
  }
  display(output,0);
}

int printf(char far *format,VARIABLE_LIST)
{
  switch(stdout.identity)
  {
    case WINDOW:
      if (!stdout.pointer)
      {
        char windowname[80];
        sprintf(windowname,"%s %x",my_TCB->name,my_TCB->stackseg);
        stdout.pointer=opendisplay(1,1,80,25,BORDER|NEWLINE,
                                   system_data,
                                   system_border,
                                   system_cursor,
                                   windowname);
      }
      return(wprintf(stdout.pointer,format,VARIABLE_LIST));
    case DISK:
    case ETHER:
    case COMM:
    case KEYBOARD:
  }
}
