
CC      =       \nipc\batch.ipc\mc

ASM     =       \nipc\batch.ipc\asm

LINK    =       \nipc\batch.ipc\ml

PCADEP  =       \nipc\pca\npca.h

COMDEP  =       \nipc\comm\comm.h

MODDEP  =       \nipc\common.ipc\mod.h\
                \nipc\common.ipc\os.h

VIDDEP  =       \nipc\video\text\video.h

DESTNAME=       osdisk.exe

!if $d(DEST)
$(DEST)\$(DESTNAME) : $(DESTNAME)
        copy $(DESTNAME) $(DEST)
!endif

$(DESTNAME) : osdisk.obj diskasm.obj
        $(LINK) osdisk diskasm

osdisk.obj : osdisk.c $(MODDEP) $(VIDDEP)
        $(CC) osdisk

