


CC      =       \nipc\batch.ipc\mc

ASM     =       \nipc\batch.ipc\asm

LINK    =       \nipc\batch.ipc\ml

PCADEP  =       \nipc\pca\npca.h

MODDEP  =       \nipc\common.ipc\mod.h\
                \nipc\common.ipc\os.h

VIDDEP  =       \nipc\video\text\video.h

ETHDEP  =       \nipc\ether\wdether\ether.h

DESTNAME=       multeth.exe

!if $d(DEST)
$(DEST)\$(DESTNAME) : $(DESTNAME)
        copy $(DESTNAME) $(DEST)
!endif

$(DESTNAME) : multeth.obj ..\multthrd.obj
        $(LINK) multeth ..\multthrd

multeth.obj : multeth.c $(MODDEP) $(VIDDEP) $(PCADEP) $(ETHDEP) ..\multthrd.h
        $(CC) multeth

..\multthrd.obj : ..\multthrd.c ..\multthrd.h $(MODDEP) $(PCADEP) $(VIDDEP)
        cd ..
        make -fmakemt
        cd multeth
